#!/usr/bin/env zsh
set -e

yarn run input:commits
yarn run input:authors
yarn run input:issues
yarn run input:pulls

yarn run input:comments:issues
yarn run input:comments:pulls

yarn run input:users

yarn run input:sentiments:commits
yarn run input:sentiments:issues
yarn run input:sentiments:pulls
yarn run input:sentiments:comments
