#!/usr/bin/env zsh
curl \
  -s \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: Bearer $GITHUB_TOKEN_COMMITOLOGY_DATA" \
  https://api.github.com/rate_limit |
  jq -r ".resources.core"
